services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: challenge3-mosquitto
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  node-red:
    image: nodered/node-red:latest
    container_name: challenge3-node-red
    network_mode: host
    restart: unless-stopped
    depends_on:
      - mosquitto
    environment:
      - TZ=Europe/Rome
      - FLOWS=flows.json
    volumes:
      - ./node-red:/data
      - /home/pitesse/Desktop/IoT:/home/pitesse/Desktop/IoT

